title: Andrey Kuznetsov
email: and.rey.q@yandex.ru

url: ""
baseurl: "" 
images_path: "/assets/img" 

# for gh-pages - without subdomain
# baseurl: "blog" 
# images_path: "/blog/assets/img" 

# social
github_username:  kuznetsovandrey76

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


